<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GalleryImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $images = [
            //OJT Batch 1-6
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_1_1.png', 'alt_text' => 'Batch 1'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_1_2.png', 'alt_text' => 'Batch 1'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_1_3.png', 'alt_text' => 'Batch 1'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_2_1.png', 'alt_text' => 'Batch 2'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_2_2.png', 'alt_text' => 'Batch 2'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_2_3.png', 'alt_text' => 'Batch 2'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_3_1.png', 'alt_text' => 'Batch 3'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_3_2.png', 'alt_text' => 'Batch 3'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_3_3.png', 'alt_text' => 'Batch 3'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_1.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_2.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_3.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_4.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_5.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_6.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_7.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_8.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_9.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_10.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_11.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_12.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_13.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_14.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_15.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_16.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_4_17.png', 'alt_text' => 'Batch 4'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_1.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_2.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_3.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_4.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_5.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_6.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_7.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_8.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_9.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_10.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_11.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_12.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_13.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_14.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_15.png', 'alt_text' => 'Batch 5'],
            ['category' => 'OJT Batch 1-6', 'image_path' => '/images/batch_5_16.png', 'alt_text' => 'Batch 5'],

            //Site Pictures
            ['category' => 'Site Pictures', 'image_path' => '/images/alto_1.jpg', 'alt_text' => 'Alto'],
            ['category' => 'Site Pictures', 'image_path' => '/images/alto_2.jpg', 'alt_text' => 'Alto'],
            ['category' => 'Site Pictures', 'image_path' => '/images/alto_3.jpg', 'alt_text' => 'Alto'],
            ['category' => 'Site Pictures', 'image_path' => '/images/alto_3.jpg', 'alt_text' => 'Alto'],
            ['category' => 'Site Pictures', 'image_path' => '/images/amadeo_1.jpg', 'alt_text' => 'Amadeo'],
            ['category' => 'Site Pictures', 'image_path' => '/images/amadeo_2.jpg', 'alt_text' => 'Amadeo'],
            ['category' => 'Site Pictures', 'image_path' => '/images/amadeo_3.jpg', 'alt_text' => 'Amadeo'],
            ['category' => 'Site Pictures', 'image_path' => '/images/amadeo_4.jpg', 'alt_text' => 'Amadeo'],
            ['category' => 'Site Pictures', 'image_path' => '/images/amadeo_5.jpg', 'alt_text' => 'Amadeo'],
            ['category' => 'Site Pictures', 'image_path' => '/images/amadeo_6.jpg', 'alt_text' => 'Amadeo'],
            ['category' => 'Site Pictures', 'image_path' => '/images/amadeo_7.jpg', 'alt_text' => 'Amadeo'],
            ['category' => 'Site Pictures', 'image_path' => '/images/amadeo_8.jpg', 'alt_text' => 'Amadeo'],
            ['category' => 'Site Pictures', 'image_path' => '/images/boystown_1.jpg', 'alt_text' => 'Boystown'],
            ['category' => 'Site Pictures', 'image_path' => '/images/boystown_2.jpg', 'alt_text' => 'Boystown'],
            ['category' => 'Site Pictures', 'image_path' => '/images/boystown_3.jpg', 'alt_text' => 'Boystown'],
            ['category' => 'Site Pictures', 'image_path' => '/images/dasma_1.jpg', 'alt_text' => 'Dasma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/dasma_2.jpg', 'alt_text' => 'Dasma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/dasma_3.jpg', 'alt_text' => 'Dasma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/dasma_4.jpg', 'alt_text' => 'Dasma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/dasma_5.jpg', 'alt_text' => 'Dasma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/dasma_6.jpg', 'alt_text' => 'Dasma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/dasma_7.jpg', 'alt_text' => 'Dasma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/dasma_8.jpg', 'alt_text' => 'Dasma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/liquigaz_1.jpg', 'alt_text' => 'Liquigaz'],
            ['category' => 'Site Pictures', 'image_path' => '/images/liquigaz_2.jpg', 'alt_text' => 'Liquigaz'],
            ['category' => 'Site Pictures', 'image_path' => '/images/liquigaz_3.jpg', 'alt_text' => 'Liquigaz'],
            ['category' => 'Site Pictures', 'image_path' => '/images/liquigaz_4.jpg', 'alt_text' => 'Liquigaz'],
            ['category' => 'Site Pictures', 'image_path' => '/images/liquigaz_5.jpg', 'alt_text' => 'Liquigaz'],
            ['category' => 'Site Pictures', 'image_path' => '/images/liquigaz_6.jpg', 'alt_text' => 'Liquigaz'],
            ['category' => 'Site Pictures', 'image_path' => '/images/liquigaz_7.jpg', 'alt_text' => 'Liquigaz'],
            ['category' => 'Site Pictures', 'image_path' => '/images/loma_1.jpg', 'alt_text' => 'Loma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/loma_2.jpg', 'alt_text' => 'Loma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/loma_3.jpg', 'alt_text' => 'Loma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/loma_4.jpg', 'alt_text' => 'Loma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/loma_5.jpg', 'alt_text' => 'Loma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/loma_6.jpg', 'alt_text' => 'Loma'],
            ['category' => 'Site Pictures', 'image_path' => '/images/malabon_1.jpg', 'alt_text' => 'Malabon'],
            ['category' => 'Si  te Pictures', 'image_path' => '/images/malabon_2.jpg', 'alt_text' => 'Malabon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/malabon_3.jpg', 'alt_text' => 'Malabon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/malabon_4.jpg', 'alt_text' => 'Malabon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/malabon_5.jpg', 'alt_text' => 'Malabon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/maragondon_1.jpg', 'alt_text' => 'Maragondon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/maragondon_2.jpg', 'alt_text' => 'Maragondon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/maragondon_3.jpg', 'alt_text' => 'Maragondon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/maragondon_5.jpg', 'alt_text' => 'Maragondon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/maragondon_5.jpg', 'alt_text' => 'Maragondon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/maragondon_6.jpg', 'alt_text' => 'Maragondon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/maragondon_7.jpg', 'alt_text' => 'Maragondon'],
            ['category' => 'Site Pictures', 'image_path' => '/images/mexico_1.jpg', 'alt_text' => 'Mexico'],
            ['category' => 'Site Pictures', 'image_path' => '/images/mexico_2.jpg', 'alt_text' => 'Mexico'],
            ['category' => 'Site Pictures', 'image_path' => '/images/narvaez_1.jpg', 'alt_text' => 'Narvaez'],
            ['category' => 'Site Pictures', 'image_path' => '/images/narvaez_2.jpg', 'alt_text' => 'Narvaez'],
            ['category' => 'Site Pictures', 'image_path' => '/images/narvaez_3.jpg', 'alt_text' => 'Narvaez'],
            ['category' => 'Site Pictures', 'image_path' => '/images/narvaez_4.jpg', 'alt_text' => 'Narvaez'],
            ['category' => 'Site Pictures', 'image_path' => '/images/narvaez_5.jpg', 'alt_text' => 'Narvaez'],
            ['category' => 'Site Pictures', 'image_path' => '/images/narvaez_6.jpg', 'alt_text' => 'Narvaez'],
            ['category' => 'Site Pictures', 'image_path' => '/images/narvaez_7.jpg', 'alt_text' => 'Narvaez'],
            ['category' => 'Site Pictures', 'image_path' => '/images/narvaez_8.jpg', 'alt_text' => 'Narvaez'],
            ['category' => 'Site Pictures', 'image_path' => '/images/narvaez_9.jpg', 'alt_text' => 'Narvaez'],
            ['category' => 'Site Pictures', 'image_path' => '/images/san_juan_1.jpg', 'alt_text' => 'San Juan'],
            ['category' => 'Site Pictures', 'image_path' => '/images/san_juan_2.jpg', 'alt_text' => 'San Juan'],
            ['category' => 'Site Pictures', 'image_path' => '/images/san_juan_3.jpg', 'alt_text' => 'San Juan'],
            ['category' => 'Site Pictures', 'image_path' => '/images/san_juan_4.jpg', 'alt_text' => 'San Juan'],
            ['category' => 'Site Pictures', 'image_path' => '/images/san_juan_5.jpg', 'alt_text' => 'San Juan'],
            ['category' => 'Site Pictures', 'image_path' => '/images/stateland_1.jpg', 'alt_text' => 'Stateland'],
            ['category' => 'Site Pictures', 'image_path' => '/images/stateland_2.jpg', 'alt_text' => 'Stateland'],
            ['category' => 'Site Pictures', 'image_path' => '/images/stateland_3.jpg', 'alt_text' => 'Stateland'],
            ['category' => 'Site Pictures', 'image_path' => '/images/ternate_1.jpg', 'alt_text' => 'Ternate'],
            ['category' => 'Site Pictures', 'image_path' => '/images/ternate_2.jpg', 'alt_text' => 'Ternate'],
            ['category' => 'Site Pictures', 'image_path' => '/images/ternate_3.jpg', 'alt_text' => 'Ternate'],
            ['category' => 'Site Pictures', 'image_path' => '/images/ternate_4.jpg', 'alt_text' => 'Ternate'],
            ['category' => 'Site Pictures', 'image_path' => '/images/ternate_5.jpg', 'alt_text' => 'Ternate'],
            ['category' => 'Site Pictures', 'image_path' => '/images/ternate_6.jpg', 'alt_text' => 'Ternate'],
        ];

        foreach($images as $image){
            \App\Models\GalleryImage::create($image);
        }
    }
}
